// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A job recommendation AI agent.
 *
 * - recommendJobs - A function that handles the job recommendation process.
 * - RecommendJobsInput - The input type for the recommendJobs function.
 * - RecommendJobsOutput - The return type for the recommendJobs function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const RecommendJobsInputSchema = z.object({
  resumeText: z
    .string()
    .describe("The text content of the job seeker's resume."),
  keywords: z
    .string()
    .optional()
    .describe('Preferred job keywords of the job seeker.'),
});
export type RecommendJobsInput = z.infer<typeof RecommendJobsInputSchema>;

const RecommendJobsOutputSchema = z.object({
  jobRecommendations: z
    .array(
      z.object({
        title: z.string().describe('The specific, recommended job title.'),
        company: z
          .string()
          .describe(
            'An example of a type of company that hires for this role (e.g., "a SaaS startup", "a large tech company").'
          ),
        reasoning: z
          .string()
          .describe(
            "A brief, 1-2 sentence explanation of why this job is a good match based on the user's profile and desired keywords."
          ),
      })
    )
    .describe('A list of semantically matched job recommendations.'),
});
export type RecommendJobsOutput = z.infer<typeof RecommendJobsOutputSchema>;

export async function recommendJobs(input: RecommendJobsInput): Promise<RecommendJobsOutput> {
  return recommendJobsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'recommendJobsPrompt',
  input: {schema: RecommendJobsInputSchema},
  output: {schema: RecommendJobsOutputSchema},
  prompt: `You are an expert career advisor and senior recruiter. Your task is to provide insightful, semantic job recommendations based on a user's resume and optional keywords.

You must perform a deep analysis of the resume, identifying specific technical skills (like Python, React, AWS, etc.) and soft skills.

Then, determine if the user is a "career changer" or an "experienced professional" seeking a new role in their current field.

1.  **Analyze Keywords vs. Resume**: Compare the user's desired keywords (if provided) with their resume experience.
    *   **If experience ALIGNS with keywords OR if specific technical skills in the resume align with the keywords**: The user is an experienced professional. Recommend roles that match their seniority (e.g., if they have 8 years of experience, suggest "Senior" or "Lead" roles, not "Junior" roles). If the resume mentions "Python", actively recommend roles that use Python.
    *   **If experience DOES NOT ALIGN with keywords**: The user is a career changer. Recommend entry-level or junior roles in the new field. Your reasoning should focus on their transferable skills (e.g., communication, project management) and how those skills bridge the gap to the new career.
    *   **If NO keywords are provided**: Base recommendations solely on their resume experience and identified skills. Suggest appropriate next-step roles in their current career path. For example, if "Python" is a prominent skill, suggest Python-related jobs.

For each recommendation, provide:
1.  **Job Title**: A specific, level-appropriate title.
2.  **Company**: A type of company that hires for this role.
3.  **Reasoning**: A concise explanation connecting their skills (both technical and transferable) and experience level to the recommended role.

**User's Resume Summary (Analyze for skills like Python, Java, etc.):**
---
{{{resumeText}}}
---

{{#if keywords}}
**User's Desired Roles (Keywords) - Use this to determine intent:**
---
{{{keywords}}}
---
{{/if}}

Provide your recommendations now in the specified format.`,
  config: {
    safetySettings: [
      {
        category: 'HARM_CATEGORY_HATE_SPEECH',
        threshold: 'BLOCK_MEDIUM_AND_ABOVE',
      },
      {
        category: 'HARM_CATEGORY_HARASSMENT',
        threshold: 'BLOCK_MEDIUM_AND_ABOVE',
      },
    ],
  },
});

const recommendJobsFlow = ai.defineFlow(
  {
    name: 'recommendJobsFlow',
    inputSchema: RecommendJobsInputSchema,
    outputSchema: RecommendJobsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);

