// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A job recommendation AI agent.
 *
 * - recommendJobs - A function that handles the job recommendation process.
 * - RecommendJobsInput - The input type for the recommendJobs function.
 * - RecommendJobsOutput - The return type for the recommendJobs function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const RecommendJobsInputSchema = z.object({
  resumeText: z
    .string()
    .describe("The text content of the job seeker's resume."),
  keywords: z
    .string()
    .optional()
    .describe('Preferred job keywords of the job seeker.'),
});
export type RecommendJobsInput = z.infer<typeof RecommendJobsInputSchema>;

const RecommendJobsOutputSchema = z.object({
  jobRecommendations: z
    .array(
      z.object({
        title: z.string().describe('The specific, recommended job title.'),
        company: z
          .string()
          .describe(
            'An example of a type of company that hires for this role (e.g., "a SaaS startup", "a large tech company").'
          ),
        reasoning: z
          .string()
          .describe(
            "A brief, 1-2 sentence explanation of why this job is a good match based on the user's profile and desired keywords."
          ),
      })
    )
    .describe('A list of semantically matched job recommendations.'),
});
export type RecommendJobsOutput = z.infer<typeof RecommendJobsOutputSchema>;

export async function recommendJobs(input: RecommendJobsInput): Promise<RecommendJobsOutput> {
  return recommendJobsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'recommendJobsPrompt',
  input: {schema: RecommendJobsInputSchema},
  output: {schema: RecommendJobsOutputSchema},
  prompt: `You are an expert career advisor specializing in helping people transition into new careers. Your task is to provide insightful, semantic job recommendations.

Analyze the user's resume to understand their background, but **give strong priority to their stated keywords**. The user's keywords indicate their desired career path, even if it's different from their past experience.

Your goal is to bridge the gap between their past and their future goals.
- If keywords are provided, focus recommendations on that field. Suggest entry-level or junior roles if their experience doesn't directly match.
- Identify transferable skills from their resume (e.g., communication, project management, analytical skills) and explain how they apply to the new role.
- If no keywords are provided, then base the recommendations on their resume.

For each recommendation, provide:
1.  **Job Title**: A specific title relevant to their desired field (or past experience if no keywords).
2.  **Company**: A type of company that hires for this role.
3.  **Reasoning**: A concise explanation connecting their transferable skills to the new role and acknowledging it may be a career change.

**User's Resume Summary:**
{{{resumeText}}}

{{#if keywords}}
**User's Desired Roles (Keywords) - PRIORITIZE THIS:**
{{{keywords}}}
{{/if}}

Provide your recommendations now in the specified format.`,
  config: {
    safetySettings: [
      {
        category: 'HARM_CATEGORY_HATE_SPEECH',
        threshold: 'BLOCK_MEDIUM_AND_ABOVE',
      },
      {
        category: 'HARM_CATEGORY_HARASSMENT',
        threshold: 'BLOCK_MEDIUM_AND_ABOVE',
      },
    ],
  },
});

const recommendJobsFlow = ai.defineFlow(
  {
    name: 'recommendJobsFlow',
    inputSchema: RecommendJobsInputSchema,
    outputSchema: RecommendJobsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
